
package com.p.service.pojo;

import static javax.persistence.GenerationType.IDENTITY;

// Generated Jul 16, 2015 5:04:23 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employeelobs generated by hbm2java
 */
@Entity
@Table(name = "topicgroups"/* , catalog = "zettaprofile" */, uniqueConstraints = @UniqueConstraint(columnNames = {
		"topicid", "groupid" }))
public class TopicGroupRelation /* implements java.io.Serializable */ {

	/**
	 * 
	 */
	// private static final long serialVersionUID = 5429095023265480024L;
	private Integer id;
	private Topic topics;
	private Group groups;

	public TopicGroupRelation() {
	}

	public TopicGroupRelation(Topic topics, Group groups) {
		super();
		this.topics = topics;
		this.groups = groups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topicid", nullable = false)
	public Topic getTopics() {
		return this.topics;
	}

	public void setTopics(Topic topics) {
		this.topics = topics;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupid", nullable = false)
	public Group getGroups() {
		return this.groups;
	}

	public void setGroups(Group groups) {
		this.groups = groups;
	}

	// @Override
	// public String toString() {
	// StringBuffer sb = new StringBuffer();
	//
	// sb.append("{").append("\"id\" :\"" + id + "\"").append(" ,
	// ").append("\"topics\" :\"" + topics.getId() + "\"").append(" , ")
	// .append("\"groups\" :\"" + groups.getId() + "\"").append("}");
	//
	// return sb.toString();
	// }

}
